# Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
np.ones(2)

array([1., 1.])

In [5]:
np.empty(4)     # np.empty akan memberikan nilai secara acak

array([1.12161262e-311, 4.87323201e+199, 1.14197842e+243, 1.06499872e-094])

In [6]:
print(np.arange(2,11,2))        # arange(angka_awal, angka_stop, interval)
print(np.arange(2))

[ 2  4  6  8 10]
[0 1]


### List vs Numpy

In [7]:
height= [1.73, 1.68, 1.71, 1.86, 1.87]
weight= [65.4, 59.2, 63.2, 88.4, 68.7]

weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [8]:
height= [1.73, 1.68, 1.71, 1.86, 1.87]
weight= [65.4, 59.2, 63.2, 88.4, 68.7]

np_height = np.array(height)
np_weight = np.array(weight)

np_weight/np_height**2

array([21.85171573, 20.97505669, 21.61348791, 25.55208695, 19.64597215])

In [9]:
height= np.array([1.73, 1.68, 1.71, 1.86, 1.87])
weight= np.array([65.4, 59.2, 63.2, 88.4, 68.7])

weight/height**2

array([21.85171573, 20.97505669, 21.61348791, 25.55208695, 19.64597215])

In [10]:
arr = np.array([1,2,3,4,5])
np.append(arr, [6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
arr = np.array([1,3,7,5])
np.append(arr, [6,7,8])

array([1, 3, 7, 5, 6, 7, 8])

In [12]:
np.delete(arr, 3)

array([1, 3, 7])

In [13]:
np.sort(arr)

array([1, 3, 5, 7])

In [14]:
array_1 = np.array([[[1,2,3,4,5,],
                    [6,7,8,9,10]],

                    [[11,12,13,14,15],
                    [16,17,18,19,20]],
                    
                    [[21,22,23,24,25],
                    [26,27,28,29,30]]])

print(array_1)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


In [28]:
print(array_1.ndim)        # 3 dimensi
print(array_1.shape)

3
(3, 2, 5)


In [29]:
scalar = np.array(32)
print(scalar)
print(scalar.ndim)          # 0 dimensi
print(scalar.shape)

32
0
()


In [24]:
vektor = np.array([1,2,3,4])    # 1 dimensi
print(vektor)
print(vektor.ndim)
print(vektor.shape)

[1 2 3 4]
1
(4,)


In [23]:
matriks = np.array([[1,2,3,4],
                    [5,6,7,8]])

print(matriks)
print(matriks.ndim)     # 2 dimensi
print(matriks.shape)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


### Reshape

In [31]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [35]:
a.reshape(3,2)      #.reshape(baris, kolom)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [33]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

### Convert

In [38]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [39]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


## SOAL LATIHAN

In [45]:
import numpy as np
x = np.arange(2, 11).reshape(3,3)
print(x)

# buat ngecek pola
print(x.shape)

# buat ngecek dimensi
print(x.ndim)

## TRIK tau dimensi, LIAT kurung kotaknya --> []

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
(3, 3)
2


In [43]:
arr = np.array(70)
print(arr)

arr.ndim

70


0

In [55]:
arr = np.array([[1,2,3], [4,5,6], [4,5,6]])
print(arr)

arr.shape

[[1 2 3]
 [4 5 6]
 [4 5 6]]


(3, 3)

In [53]:
arr = np.array([[[1,2,3],
                [4,5,6]],
                
                [[1,2,3],
                [4,5,6]]])
print(arr)

arr.shape

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


(2, 2, 3)

In [65]:
array_tes = np.array([[3,7,10,2], [3,7,10,2]], ndmin=4)         # ndmin untuk mengatur suatu dimensi
print(array_tes)

array_tes.ndim

[[[[ 3  7 10  2]
   [ 3  7 10  2]]]]


4

In [69]:
arr = np.array([3,10,3,2])

print(arr[3] + arr[2])

5


In [71]:
arr = np.array([[6,7,8,9,10], [1,2,3,4,5]])

print(arr[1, 3])

4


In [91]:
arr = np.array([[[1,2,3], [4,5,6]],
                [[7,8,9], [10,11,12]]])

print(arr[:, 1, 2])         # <-- (:) artinya ambil keseluruhannya. Akan sama artinya dengan (0:)

arr.shape

[ 6 12]


(2, 2, 3)

In [99]:
print(arr[:3, 1, 1])         # kalau bloknya lebih dari array yg tersedia masih tetap bisa di eksekusi

[ 5 11]


In [100]:
print(arr[:1, :2, 1])

[[2 5]]


In [101]:
print(arr[:3, :2, 1])

[[ 2  5]
 [ 8 11]]


In [104]:
print(arr[:1, :2, :1])

[[[1]
  [4]]]


In [116]:
arr = np.array([4,5,6,7,1,2,3])

print(arr[1:6:2])       # 1:6 <-- dari indeks ke-1 - ke-5; :4 <-- loncat 2 indeks
                        #        5,6,7,1,2       ---------->        5,7,2

[5 7 2]


In [117]:
arr = np.array([2,2,7,4,5,6,7,8,10])

print(arr[2:8:3])       # START : END : STEP
print(arr[::3])         # tidak di definisikan indeksnya, jadi langsung loncat 3 indeks

[7 6]
[2 4 7]


In [118]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [137]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(1,2,-1)        # -1 maksudnya unknown dimension
print(newarr, "\n")
print(newarr.shape)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]] 

(1, 2, 6)


### Tambahan

In [139]:
def convert(fahr):
    cels = fahr * 1.8 + 32.0
    return cels

print(convert(32))

89.6


In [140]:
def convert(fahr, kelv):
    cels = fahr * 1.8 + 32.0
    cels2 = kelv - 273.15
    return cels

print("Temperature in celcius (C) =", convert(32,20))

Temperature in celcius (C) = 89.6


In [141]:
def fahr_to_celcius(temp):
    return (temp -32) * (5/9)
print(fahr_to_celcius(72))

22.22222222222222


In [144]:
def temp_converter(ktemp):
    ctemp = ktemp - 273.15
    ftemp = ctemp * (9/5) + 32
    return [ktemp, ctemp, ftemp]

print(temp_converter(296))

[296, 22.850000000000023, 73.13000000000005]
