In [1]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]

In [2]:
a + b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
import numpy as np

In [5]:
vect_a = np.array(a)
vect_b = np.array(b)

In [6]:
vect_a + vect_b

array([ 7,  9, 11, 13, 15])

## Vector Norm

In [8]:
vect_a = np.array([3,4])
np.linalg.norm(vect_a, 1)

7.0

## Operasi Penjumlahan/Pengurangan/Pembagian

In [10]:
a = [1,2,3]
vect_a = np.array(a)
vect_a

array([1, 2, 3])

In [16]:
## Dengan bilangan

In [12]:
vect_a + 2

array([3, 4, 5])

In [13]:
vect_a - 2

array([-1,  0,  1])

In [14]:
vect_a / 2

array([0.5, 1. , 1.5])

In [15]:
## Antar vector

In [17]:
b = [10,11,12]
vect_b = np.array(b)
vect_b

array([10, 11, 12])

In [18]:
vect_a / vect_b

array([0.1       , 0.18181818, 0.25      ])

In [19]:
c = [10,11]
vect_c = np.array(c)
vect_c

array([10, 11])

In [22]:
vect_a - vect_c

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

## Perkalian

In [31]:
# Dengan bilangan

In [26]:
print(vect_a)
print(vect_b)

[1 2 3]
[10 11 12]


In [27]:
vect_a * vect_b

array([10, 22, 36])

In [28]:
vect_a.dot(vect_b)

68

In [29]:
np.dot(vect_a, vect_b)

68

In [30]:
vect_a@vect_b

68

## Cosine Similarity

`Digunakan untuk mencari kemiripan antar vektor`

In [33]:
vect_f = np.array([4, 0])
vect_g = np.array([6,0])


In [35]:
cos_theta = (vect_f.dot(vect_g)) / (np.linalg.norm(vect_f) * np.linalg.norm(vect_g))
cos_theta

1.0

In [36]:
rad = np.arccos(cos_theta)
rad

0.0

In [37]:
degree = np.degrees(rad)
degree

0.0

# Studi Kasus

```
teks_1 = saya pergi ke rumah nenek saya
teks_2 = saya pergi ke rumah kakek saya
```

Liat keterangan data di catetan evernote

In [38]:
teks_1 = [2,1,1,1,1,0]
teks_2 = [2,1,1,1,0,1]

vect_t1 = np.array(teks_1)
vect_t2 = np.array(teks_2)

In [40]:
cos_theta = (vect_t1.dot(vect_t2)) / (np.linalg.norm(vect_t1) * np.linalg.norm(vect_t2))
cos_theta

0.8749999999999998

Sebenarnya idak ada ambang batas kemiripan dalam cosinus similiarity
```
> 0,5 sudah tergolong mirip
> 0,8 sudah tergolong sangat mirip
```

In [42]:
rad = np.arccos(cos_theta)
rad

0.5053605102841577

In [44]:
degree = np.degrees(rad)
degree

28.955024371859874

# Studi Kasus 2

```
teks_3 = Selamat pagi ibu dunia
teks_4 = Nusantara ibu kota baru

In [48]:
teks_3 = [1,1,1,0,1,0,0]
teks_4 = [0,0,0,1,1,1,1]

vect_t3 = np.array(teks_3)
vect_t4 = np.array(teks_4)

In [49]:
cos_theta = (vect_t3.dot(vect_t4)) / (np.linalg.norm(vect_t3) * np.linalg.norm(vect_t4))
cos_theta

0.25

Tidak ada kemiripan antar vektor jika memiliki nilai cos theta