In [1]:
import numpy as np

# 1. Membuat vektor dalam Python

In [4]:
x = [17, 22, 19]

vect_x = np.array(x)
vect_x

array([17, 22, 19])

# 2. Operasi perhitungan dalam vektor

In [5]:
a = [17, 22, 19]
b = [10, 20, 11]
c = [5, 12, 9]

vect_a = np.array(a)
vect_b = np.array(b)
vect_c = np.array(c)

## 2a. A + B

In [7]:
vect_a + vect_b

array([27, 42, 30])

## 2b. B - C

In [8]:
vect_b - vect_c

array([5, 8, 2])

## 2c. A dot C

In [9]:
vect_a.dot(vect_c)

520

## 2d. A x B

In [10]:
vect_a * vect_b

array([170, 440, 209])

## 2e. Vector Norm A

In [11]:
np.linalg.norm(vect_a)

33.67491648096547

## 2f. Sudat antara vektor A dan B

In [12]:
cos_theta = (vect_a.dot(vect_b)) / (np.linalg.norm(vect_a) * np.linalg.norm(vect_b))
cos_theta

0.9759590023331435

In [13]:
rad = np.arccos(cos_theta)
rad

0.21971776576153962

In [16]:
degree = np.degrees(rad)
degree

12.588900662180242