In [1]:
import numpy as np

In [5]:
v = np.array([[1,2,3], [1,0,3]])
v

array([[1, 2, 3],
       [1, 0, 3]])

In [6]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[1,2,3], [4,5,6]])

In [8]:
C = A + B
C

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [9]:
C = A - B
C

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
k = 2
D = k * A
D

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [16]:
from numpy import array

In [17]:
A = array([[1,2,3], [4,5,6]])
B = array([[1,2,1], [0,2,3]])

In [18]:
C = A * 3
C

array([[ 3,  6,  9],
       [12, 15, 18]])

In [19]:
A = array([[1,2], [3,4], [5,6]])
B = array([[1,2], [3,4]])

In [20]:
C = A.dot(B)
C

array([[ 7, 10],
       [15, 22],
       [23, 34]])

In [21]:
D = A @ B
D

array([[ 7, 10],
       [15, 22],
       [23, 34]])

In [22]:
import numpy as np

In [23]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[1,2,1], [1,2,3]])

In [24]:
C = A / B
C

array([[1. , 1. , 3. ],
       [4. , 2.5, 2. ]])

In [25]:
from numpy import array

In [27]:
A = array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
C = A.T
C

array([[1, 3, 5],
       [2, 4, 6]])

In [29]:
from numpy import array
from numpy.linalg import inv

In [31]:
A = array([[1.0, 2.0], [3.0, 4.0]])
A

array([[1., 2.],
       [3., 4.]])

In [32]:
B = inv(A)
B

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [33]:
from numpy import array
from numpy.linalg import det

In [34]:
A = array([[1,2,3], [4,5,6], [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
B = det(A)
print(B)

-9.51619735392994e-16


In [38]:
from numpy import array

T = array([[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])

print(T.shape)
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
