In [1]:
import numpy as np
from numpy import array

In [7]:
T = array([[1,2], [2,4]])
print(T)

a = array([[1], [1]])
print(a)

b = array([[1], [2]])
print(b)

[[1 2]
 [2 4]]
[[1]
 [1]]
[[1]
 [2]]


In [9]:
a1 = T.dot(a)
print(a1)

b1 = T.dot(b)
print(b1)

[[3]
 [6]]
[[ 5]
 [10]]


## Eigendecomposition

In [10]:
from numpy import array
from numpy.linalg import eig

In [11]:
A = array([[1,2,3], [4,5,6], [7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
values, vectors = eig(A)

In [14]:
print(values)

[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]


In [15]:
print(vectors)

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [17]:
B = array([[1,2], [2,4]])
B

array([[1, 2],
       [2, 4]])

In [18]:
values, vectors = eig(B)

In [19]:
values

array([0., 5.])

In [20]:
vectors

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

## Reconstruct matrix

In [21]:
from numpy import diag
from numpy.linalg import eig,inv

In [23]:
values, vectors = eig(A)
B = vectors.dot(diag(values)).dot(inv(vectors))
B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

## Studi Kasus

In [24]:
N = [[0,0,0,1,0,0],
    [0.25,0,0,0,0,0],
    [0.25,0,0,0,0,0],
    [0,0,0,0,1,0],
    [0.25,0,0,0,0,0],
    [0.25,1,1,0,0,0]]

N = np.array(N)

In [25]:
print(N)

[[0.   0.   0.   1.   0.   0.  ]
 [0.25 0.   0.   0.   0.   0.  ]
 [0.25 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   1.   0.  ]
 [0.25 0.   0.   0.   0.   0.  ]
 [0.25 1.   1.   0.   0.   0.  ]]


mengolah eigen value dan eigen vector nya

In [26]:
eigval, eigvec = eig(N)

In [27]:
eigval

array([ 0.        +0.j        ,  0.        +0.j        ,
        0.        +0.j        , -0.31498026+0.54556182j,
       -0.31498026-0.54556182j,  0.62996052+0.j        ])

cari yang memiliki nilai eigen value tertinggi

In [29]:
eigval.argmax()

5

identifikasi eigen vector di indeks ke 5

In [30]:
eigvec[5]

array([ 1.        +0.j, -1.        +0.j, -1.        +0.j,  0.63225405+0.j,
        0.63225405-0.j, -0.77128308+0.j])

In [32]:
eigvec[5].argmax()  # argmax() untuk mengetahui lokasi yang bernilai tinggi ada dimana

0

In [34]:
eigvec[5].max()     # max() hanya untuk mengetahui nilai yang tertingginya

(1+0j)