## 1. Membuat tensor

In [1]:
from numpy import array

In [23]:
T = array([[[23,50], [7,12]], [[57,67], [99,43]], [[75,21], [57,12]], [[87,26], [18,84]]])
print(T)
print(T.shape)

[[[23 50]
  [ 7 12]]

 [[57 67]
  [99 43]]

 [[75 21]
  [57 12]]

 [[87 26]
  [18 84]]]
(4, 2, 2)


## 2. Perkalian Matrix

In [10]:
A = array([[23,50,19], [7,12,109], [57,67,98]])
B = array([[17], [22], [19]])

print(A)
print(A.shape)
print(B)
print(B.shape)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
(3, 3)
[[17]
 [22]
 [19]]
(3, 1)


In [11]:
C = A.dot(B)
print(C)
print(C.shape)

[[1852]
 [2454]
 [4305]]
(3, 1)


## 3. Transpose, Determinan, dan Inverse

In [13]:
print(A)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]


### Transpose

In [14]:
transpose = A.T
print(transpose)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


### Determinan

In [15]:
from numpy.linalg import det

In [16]:
B = det(A)
print(B)

131344.0000000002


### Inverse

In [17]:
from numpy.linalg import inv

In [18]:
C = inv(A)
print(C)

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
